import Foundation

var progress = MissionProgress()
progress.advanceLesson()
progress.recordDemoDrop()
assert(progress == MissionProgress(), "Cannot skip sorting")
progress.answerSorting(keepPlasticOut: false)
assert(progress.step == .sort, "Wrong answer must not advance")
progress.answerSorting(keepPlasticOut: true)
assert(progress.step == .drop && progress.demoDrops == 0)
progress.recordDemoDrop()
progress.recordDemoDrop()
assert(progress.demoDrops == 1 && progress.step == .digestion, "No double credit")
progress.advanceLesson()
assert(!progress.lightUnlocked)
progress.advanceLesson()
assert(progress.lightUnlocked)
progress.advanceLesson()
assert(progress.demoDrops == 1)
let saved = try JSONEncoder().encode(progress)
assert(MissionProgress.restore(saved) == progress, "Reward survives save/restore")
assert(MissionProgress.restore(Data("broken".utf8)) == MissionProgress())
assert(MissionProgress.restore(Data("{\"step\":4,\"demoDrops\":0}".utf8)) == MissionProgress())
print("Passed: mission gating, wrong answer, duplicate prevention, reward, persistence and invalid save checks")
